title: "Real-Time AI Fraud Detection for Digital Payments"
description: "Final Year Project - Developing an intelligent system to detect payment fraud in real-time using machine learning and stream processing"
baseurl: "/real-time-fraud-detection-fyp"
url: "https://yourusername.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Custom variables
supervisor: "Dr. Supervisor Name"
student: "Your Name"
course: "COMP4801/FITE4801 Final Year Project"
academic_year: "2025-2026"
university: "Your University Name"

# Navigation
header_pages:
  - index.md
  - project-overview.md
  - methodology.md
  - progress.md
  - results.md
  - demo.md
  - documentation.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
